name: closet
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.2
  flutter_launcher_icons: ^0.14.1
  http: ^1.2.2
  shared_preferences: ^2.0.15
  image_picker: ^1.1.2
  logger: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

# flutter_native_splash와 flutter_icons 설정은 flutter 블록 외부에 위치
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/logo.png
  branding: assets/brandlogo.png
  branding_mode: stretch
  android: true
  ios: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"

dependency_overrides:
  protobuf: ^3.0.0
